services:
  core-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ticketlemon-core-service
    ports:
      - "8003:8003"
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}